# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.20.1
	yarn_mappings=1.20.1+build.10
	# loader_version=0.14.22
	loader_version=0.17.2

# Mod Properties
	mod_version = 1.20.1-0.0.26
	maven_group = net.zuiron
	archives_base_name = photosynthesis

# Dependencies
	# fabric_version=0.92.0+1.20.1
	# fabric_version=0.92.2+1.20.1
    fabric_version=0.92.6+1.20.1

# REI Properties
	rei_version=12.1.785

# JEI Properties
	jei_version=15.2.0.27

# Patchouli
	patchouli_version=1.20.1-84.1-FABRIC

# Cloth Config
	cloth_config_version=11.1.136

# Mod Menu
	modmenu_version=7.2.2

# WTHIT
	wthitVersion=8.16.3
	badpacketsVersion=0.4.3

# Java to use
#	org.gradle.java.home=/usr/lib/jvm/java-16-openjdk